config/routes.rb
Rails.application.routes.draw do

get "/log-in" => "sessions#new"
post "/log-in" => "sessions#create"
get "/log-out" => "sessions#destroy", as: :log_out

get  "/mylist" => "items#show"
post  "/mylist" => "items#show"
get  "/new" => "items#new"
post  "/new" => "items#create"
get "/edit" => "items#edit"
post "/edit" => "items#update"
delete "/mylist" => "items#destroy"
get "/others" => "items#others"
post "/others" => "items#others"
get "/purchases" => "items#purchases"
post "/purchases" => "items#purchases"
get "/mypurchases" => "items#mypurchases"
get "/settings" => "items#settings"
post "/settings" => "users#update"
delete "/settings" => "users#destroy"

post "/mypurchases" => "purchases#create"
delete "/mypurchases" => "purchases#destroy"

resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

	def userList(user_id=nil, item_id=nil)
		if user_id
			items = Item.where(:user_id => user_id, :deleted => false)
		else
			items = Item.where(:id => item_id, :deleted => false)
		end
		s = []
		items.each do |i|
				s.push([i.item_name, i.price, i.link, i.id, i.user_id])
		end
		s
	end

	def othersList(nameID)
		names = User.pluck("DISTINCT id")
		names.delete(nameID)
		items = []
		names.each do |n|
			items.push(self.userList(n))
		end
		list = []
		items.each do |i|
			i.each do |j|
				list.push(j)
			end
		end
		list
	end

end

app/models/purchase.rb
class Purchase < ApplicationRecord


	def status(item_id)
		if Purchase.exists?(:item_id => item_id)
			difference = self.amountDifference(item_id)
			if difference == 0
				["$0", "Yes"]
			else
				["$" + difference.round(2).to_s, "Partial"]
			end
		else
			["$" + Item.where(:id => item_id).first.price.to_s, "No"]
		end
	end

	def submit(purchase, p_amount)
		#purchase = [item_id, user_id, "Full" or "Partial"]
		p = purchase.split(" ")
		difference = self.amountDifference(p[0])
		if p[2] == "Full"
			a = Purchase.create(:item_id => p[0], :user_id => p[1],:amount => difference, :deleted => false)
			a.save
		elsif p[2] == "Partial" && difference >= p_amount.to_f
			a = Purchase.create(:item_id => p[0], :user_id => p[1], :amount => p_amount, :deleted => false)
			a.save
		end

	end

	def amountDifference(i_id)
		if Purchase.exists?(:item_id => i_id)
			price = (Item.find_by id: i_id).price
			total = Purchase.where(:item_id => i_id).sum(:amount)

			(price.to_f-total.to_f).round(2)
		else
			(Item.find_by id: i_id).price
		end
		#price = 
	end


end

app/models/user.rb
class User < ActiveRecord::Base

 attr_accessor :password
 validates_confirmation_of :password
 validates :email, :email_format => {:message => 'nope'}
 validates :password, presence: true
 validates :name, presence: true
 validates_uniqueness_of :email
 before_save :encrypt_password
 before_save :downcase_email

 def downcase_email
 	self.email.downcase!
 end

 def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt
  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
 end

 def self.authenticate(email, password)
 	email.downcase!
 	user = User.where(email: email).first
 	if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
 		user
 	end
 end


def self.cleanup(user_id)
	#pull all of the user's items then mark for deletion
	items = Item.where(user_id: user_id)
	item_id = []
	items.each do |i|
		item_id.push(i.id)
		i.deleted = true
		i.save
	end
	#pull all purchases made on the user's items
	purchases = Purchase.where(item_id: item_id)
	#pull all purchases made by that user
	myPurchases = Purchase.where(user_id: user_id)
	#if there are purchases made on the user's items, mark for deletion
	if !purchases.empty?
		purchases.each do |p|
			p.deleted = true
			p.save
		end
	else
	#if not, destroy the item
		Item.where(user_id: user_id).destroy_all
	end
	#run through the users purchases, delete the purchase then delete the item if it is marked for deletion and there is only 1 purchase
	myPurchases.each do |mp|
		if Item.where(id: mp.item_id).first.deleted == true && Purchase.where(item_id: mp.item_id).count == 1
			Item.where(id: mp.item_id).destroy_all
		end
		mp.destroy
	end


	User.where(id: user_id).destroy_all
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception

helper_method :current_user

before_action :require_login

  	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_login
		if !self.current_user
			redirect_to log_in_path
		end
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	
	def show
		@item = Item.new
		@delete = params[:delete]
		@id = params[:item_id]
	end

	def create
		@item = Item.new(item_params)
		@item.save
		puts @item.id
		flash[:notice] = "Item Added"
		redirect_to new_path
	end

	def edit
		@item = Item.new
		@item = @item.userList(nil,params[:item_id])[0]
	end

	def update
		
		Item.update(params[:item_id], :item_name => params[:item_name], :price => params[:price], :link => params[:link])
		redirect_to mylist_path
	end

	def destroy
		Item.update(params[:item_id], :deleted => true)
		#check if purchases exist, do the below if so, delete the item if not
		if Purchase.exists?(:item_id => params[:item_id])
			Purchase.where(:item_id => params[:item_id]).update_all(:deleted => true)
		else
			Item.find(params[:item_id]).destroy
		end
		redirect_to mylist_path
	end

	def others
		@items = Item.new
		@name = User.new
		@purchase = Purchase.new
	end

	def purchases
		@item = params[:items]
		@purchase = Purchase.new
		@contribute = Purchase.where(:item_id => params[:items])
	end

	def mypurchases
		@purchases = Purchase.where(:user_id => current_user.id, :deleted => false)
		@deleted = Purchase.where(:user_id => current_user.id, :deleted => true)
	end

	def settings

	end

  private
  	def item_params
  		params.permit(:item_name, :price, :link, :user_id, :deleted)
  	end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

	def create
		
		@p = Purchase.new
		if params[:purchase]
			@p.submit(params[:purchase], params[:p_amount])
			redirect_to mypurchases_path
		else
			flash[:notice] = "Item not purchased. Please select Full or Partial when submitting"
			redirect_to others_path
		end
	end

	def destroy
		
		myPurchase = Purchase.where(:id => params[:purchase]).first
		puts myPurchase.item_id
		allPurchases = Purchase.where(:item_id => myPurchase.item_id)
		puts allPurchases.count

		if allPurchases.count == 1
			myPurchase.destroy
			item = Item.where(:id => myPurchase.item_id).first
			if item.deleted
				item.destroy
			end
		else
			myPurchase.destroy
		end
		redirect_to mypurchases_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	layout "sessions"
	skip_before_action :require_login

	def create
		@user = User.authenticate(params[:email], params[:password])

		if @user
			session[:user_id] = @user.id
			redirect_to mylist_path
		else
			flash[:alert] = "Unable to log in"
			redirect_to log_in_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:logout] = "Logged out"
		redirect_to log_in_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "sessions"
  skip_before_action :require_login

  def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "Account created"
  		redirect_to log_in_path
  	else
  		flash[:alert] = "Account not created"
  		redirect_to new_user_path
  	end

  end

  def destroy
    if User.authenticate(User.find(current_user.id).email, params[:password])
      User.cleanup(current_user.id)
      redirect_to log_out_path
    else
      redirect_to settings_path
    end
  end

  def update
    if User.authenticate(User.find(current_user.id).email, params[:current_password]) && params[:new_password] != ""  
      user = User.find(current_user.id)
      user.password = params[:new_password]
      user.save
      flash[:notice] = "Password Updated"
    else
      params[:new_password] == "" ? flash[:error] = "New password cannot be blank" : flash[:error] = "Incorrect Password"
    end
      #puts params[:current_password]
      #puts params[:new_password]
    redirect_to settings_path
  end

private 

def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/items/edit.html.erb
<% if current_user.id != @item[4] %>
	<br>
	<%= "You do not own this item" %>
	<br>
	<br>
	<%= link_to "Back", mylist_path %>
<% else %>
	<P> Enter Item </p>
	<br>
	<%= form_tag edit_path do %>
		<%= label_tag("Itemname") %>
		<%= text_field_tag(:item_name, @item[0]) %>
		<br>
		<%= label_tag "Price" %>
		<%= number_field_tag(:price, @item[1], :step => 0.01) %>
		<br>
		<%= label_tag "Link" %>
		<%= url_field_tag :link, @item[2] %>
		<br>
		<%= hidden_field_tag(:item_id, @item[3]) %>
		<br>
		<%= submit_tag "Update" %>
	<% end %>
	<br> 
	<%= link_to "Back", mylist_path %>
<% end %>

app/views/items/mypurchases.html.erb
<br>
<%= form_tag(mypurchases_path, method: "delete") do %>

<% if !@purchases.first.blank? %>

<table>
	<th> </th>
	<th> Name </th>
	<th> Item </th>
	<th> Link </th>
	<th> Amount </th>
	<th> Remaining </th>
	<% @purchases.each do |p| %>
		<tr>
			<td> <%= radio_button_tag "purchase", p.id %> </td>
			<td> <%= (User.where(:id => (Item.where(:id => p.item_id).first).user_id).first).name %> </td>
			<td> <%= (Item.where(:id => p.item_id).first).item_name %> </td>
			<td>
				<%= link_to (Item.where(:id => p.item_id).first).link, (Item.where(:id => p.item_id).first).link, :target => '_blank' %> 
			</td>
			<td> 
				<% Purchase.where(:item_id => p.item_id).each do |i| %> 
					<%=  "(" + number_to_currency(i.amount) + ") " %>
					<%= ((User.where(:id => i.user_id).first).name) == current_user.name ? "You" : (User.where(:id => i.user_id).first).name %>
					<br>
				<% end %>
			</td>
			<td> <%= number_to_currency(p.amountDifference(p.item_id)) %> </td>
		</tr>
	<% end %>
</table>
<%= submit_tag "Delete", data: {confirm: "Are you sure?"} %>
<% end %>
<br>
<br>

<% if !@deleted.first.blank? %>
	<%=  %>
	<%= "These are items that you have purchased but have since been deleted by the owner" %>
	<table>
		<th> </th>
		<th> Name </th>
		<th> Item Name </th>
		<th> Amount </th>
			<% @deleted.each do |d| %>
				<tr>
					<td> <%= radio_button_tag "purchase", d.id %> </td>
					<% if (User.where(:id => (Item.where(:id => d.item_id).first).user_id).first).blank? %>
						<td> Name Deleted </td>
					<% else %>
						<td> <%= (User.where(:id => (Item.where(:id => d.item_id).first).user_id).first).name %> </td>
					<% end %>
					<td> <%= (Item.where(:id => d.item_id).first).item_name %> </td>
					<td> <%= number_to_currency(d.amount) %></td>
				<tr>
			<% end %>

	</table>
<br>
<%= submit_tag "Delete", data: {confirm: "Are you sure?"} %>
<% end %>


<% end %>

app/views/items/new.html.erb
<br>
<% if flash[:notice] %>
	<div id = "message"> <%= flash[:notice] %> </div>
<% end %>

<div id = "content">
<P> Enter Item </p>
<br>
<%= form_tag new_path do %>
	<%= label_tag("Itemname") %>
	<%= text_field_tag "item_name" %>
	<br>
	<%= label_tag "Price" %>
	<%= number_field_tag(:price, nil, :step => 0.01) %>
	<br>
	<%= label_tag "Link" %>
	<%= url_field_tag :link %>
	<br>
	<%= hidden_field_tag(:user_id, current_user.id) %>
	<br>
	<%= hidden_field_tag(:deleted, false) %>
	<br>
	<%= submit_tag "Add" %>
<% end %>
<br>
<br>
<%= link_to "Back", mylist_path %>
</div>

app/views/items/others.html.erb
<br>
<% if flash[:notice] %>
	<div id = "error"> <%= flash[:notice] %>	</div>
<% end %>


<%= form_tag purchases_path do %>
<table>
	<tr>
		<th> </th>
		<th> Name </th>
		<th> Item </th> 
		<th> Price </th> 
		<th> Link </th>
		<th> Remaining </th>
		<th> Purchased? </th>
	</tr>
	<% @items.othersList(current_user.id).each do |i| %>
		<tr>
			<td> <%= radio_button_tag "items[]", i[3]%> </td>
			<td> <%= (User.find_by id: i[4]).name %> </td>
			<td> <%= i[0] %> </td>
			<td> <%= i[1] %> </td>
			<td> <%= link_to i[2], i[2], :target => '_blank' %> </td>				
			<td> <%= @purchase.status(i[3])[0] %> </td>
			<td> <%= @purchase.status(i[3])[1] %> </td>
		</tr>
	<% end %>
</table>
<%= submit_tag "Purchase" %>
<% end %>

app/views/items/purchases.html.erb
<%= form_tag mypurchases_path do %>
<br>
<br>
<table>
	<th> Name </th>
	<th> Item </th>
	<th> Price </th>
	<th> Link </th>
	<th> Purchase </th>
	<% @item.each do |i| %>
		<tr>
			<td> <%= (User.find_by id: (Item.find_by id: i).user_id).name %> </td>
			<td> <%= (Item.find_by id: i).item_name %> </td>
			<td> <%= "$" + (Item.find_by id: i).price.to_s %> </td>
			<td> <%= link_to (Item.find_by id: i).link, (Item.find_by id: i).link, :target => '_blank' %> </td>
			<td> 
				<%= radio_button_tag :purchase, [i, current_user.id, "Full"] %> 
				<%= label_tag :purchase, "Full" %>
				<%= text_field_tag :f_amount, @purchase.amountDifference(i), readonly: true%>
				<%= radio_button_tag :purchase, [i, current_user.id, "Partial"] %>
				<%= label_tag :purchase, "Partial" %>
				<%= text_field_tag :p_amount, nil %>
				<%= submit_tag "Purchase" %>

			</td>
		</tr>

	<% end %>

</table>
<% end %>
<p>
	Contributors
</p>
<table>
	<th> Name </th>
	<th> Amount </th>
	<% @contribute.each do |c| %>
		<tr>
			<td> <%= (User.where(:id => c.user_id).first).name %> </td>
			<td> <%=  number_to_currency(c.amount) %> </td>
		</tr>
	<% end %>
</table>


<br>
<br>

<br>
<br>
<%= link_to "Back", others_path %>

app/views/items/settings.html.erb
<br>
<% if flash[:notice] %>
	<div id = "message"> <%= flash[:notice] %> </div>
<% elsif flash[:error] %>
	<div id = "error"> <%= flash[:error] %> </div>
<% end %>

<b> Change Password </b>
<br>
<%= form_tag(settings_path, method: "post") do %>
	<%= label_tag "Current Password" %>
	<%= text_field_tag :current_password %>
	<br>
	<%= label_tag "New Password" %>
	<%= text_field_tag :new_password %>
	<br>
	<%= submit_tag "Update" %>
<% end %>
<br>
<br>
<br>
<b> Delete Account </b>
<%= form_tag(settings_path, method: "delete") do %>
	<%= label_tag "Password" %>
	<%= text_field_tag :password %>
	<%= submit_tag "Delete", data: {confirm: "Are you sure you want to delete your account?"} %>
<% end %>

app/views/items/show.html.erb
<br>
<table>
	<tr>
		<th> Item Name </th>
		<th> Price </th>
		<th> Link </th>
	</tr>
	<% @item.userList(current_user.id).each do |i| %>
		<tr>
			<td>
				<%= i[0] %>
			</td>
			<td>
				<%= number_to_currency(i[1]) %>
			</td>
			<td>
				<%= link_to i[2], i[2], :target => '_blank' %>
			</td>
			<td>
				<%= link_to "edit", edit_path(:item_id => i[3]) %>
			</td>
			<td>
				<% if i[3].to_s == @id%>
					<%= button_to "Yes", mylist_path(:item_id => i[3]), :method => :delete %>
					<%= button_to "No", mylist_path %>
				<% else %>
					<%= link_to "delete", mylist_path(:item_id => i[3], :delete => "true") %>
				<% end %>
			</td>
			
		</tr>
	<% end %>
</table>
<br>
<br>
<%= link_to "Add", new_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giftlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li class="<%= 'active' if current_page?(mylist_path) %>"><%= link_to 'My List', mylist_path %></li>
      <li class="<%= 'active' if current_page?(others_path) %>"><%= link_to 'Others', others_path %></li>
      <li class="<%= 'active' if current_page?(mypurchases_path) %>"><%= link_to 'Purchases', mypurchases_path %></li>
      <li class="<%= 'active' if current_page?(settings_path) %>"><%= link_to 'Settings', settings_path %></li>
      <li style ="float:right"> <%= link_to "Log Out", log_out_path %> </li>
    </ul>
      <br>
    <div id = "content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/sessions.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giftlist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  		<%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<br>
<% if flash[:alert] %>
	<div id = "error"> <%= flash[:alert] %> </div>
<% end %>



<p> Sign-Up </p>


<%= form_for User.new do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%=f.label :email %>
	<br>
	<%=f.text_field :email %>
	<br>
	<%=f.label :password %>
	<br>
	<%=f.password_field :password %>
	<br>
	<%=f.label :password_confirmation %>
	<br>
	<%=f.password_field	:password_confirmation %>
	<br>
	<%= f.submit "Create Account" %>
<% end %>
<br>
<%= link_to "Back", log_in_path %>